apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: kubernetes-dashboard
type: Opaque
data:
  RABBITMQ_USER: cmFiYml0bXE=
  RABBITMQ_PASSWORD: cmFiYml0bXE=
  RABBITMQ_MEM_LIMIT: NTEyTWk=
