replicaCount: 3
namespace: redis-cluster

image:
  repository: redis
  tag: "alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379

persistence:
  storageClass: "standard"
  accessMode: ReadWriteOnce
  size: 1Gi

