version: "3.8"

volumes:
  redisdata:
    driver: local

networks:
  default:
    name: redis
    external: false

services:
  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - 6379:6379
    environment:
      - REDIS-PWD=${REDIS_PASSWORD}
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 10
    mem_limit: ${REDIS_MEM_LIMIT}
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    ports:
      - 8081:8081
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 10
