---
apiVersion: v1
kind: Service
metadata:
  name: hit-counter-lb
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
      app: hitcounter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hit-counter-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hitcounter
  template:
    metadata:
      labels:
        app: hitcounter
    spec:
      containers:
      - name: hitcounter
        image: calinrus/api-redis-ha:1.0
        ports:
        - containerPort: 5000