apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-0
  namespace: redis-ns
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 6379
  selector:
    statefulset.kubernetes.io/pod-name: redis-cluster-0

---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-1
  namespace: redis-ns
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 6379
  selector:
    statefulset.kubernetes.io/pod-name: redis-cluster-1

---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-2
  namespace: redis-ns
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 6379
  selector:
    statefulset.kubernetes.io/pod-name: redis-cluster-2

---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-3
  namespace: redis-ns
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 6379
  selector:
    statefulset.kubernetes.io/pod-name: redis-cluster-3

---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-4
  namespace: redis-ns
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 6379
  selector:
    statefulset.kubernetes.io/pod-name: redis-cluster-4

---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-5
  namespace: redis-ns
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 6379
  selector:
    statefulset.kubernetes.io/pod-name: redis-cluster-5
