version: '3.8'

volumes:
  elasticsearch-data:
  kibanadata:

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: elasticsearch-0
    restart: always
    network_mode: host
    environment:
      - cluster.name=${CLUSTER_NAME}
      - node.name=elasticsearch-0
      - discovery.seed_hosts=172.19.134.143:9300,172.19.134.144:9300,172.19.134.145:9300
      - cluster.initial_master_nodes=elasticsearch-0,elasticsearch-1,elasticsearch-2
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=${LICENSE}
      - ELASTIC_PASSWORD = ${ELASTIC_PASSWORD}
    ports:
      - "${ES_PORT}:9200"
      - "${SEED_PORT}:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    mem_limit: ${ES_MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:${ES_PORT}"]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    deploy:
      mode: replicated
      replicas: 1  
      placement:
        constraints: [node.role == worker] 
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - ELASTICSEARCH_USERNAME=elastic  # Varsay覺lan kullan覺c覺
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}  # Elasticsearch parolas覺
      - xpack.security.enabled=true
    ports:
      - "5601:5601"
    volumes:
      - kibanadata:/usr/share/kibana/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'"]
      interval: 10s
      timeout: 10s
      retries: 120
