services:
  redis-master3:
    image: redis:${REDIS_VERSION}
    container_name: redis-master3
    hostname: redis-master3
    network_mode: host
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-enabled", "yes", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}", "--masterauth", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./master1/data:/data
      - ./master1/redis.conf:/usr/local/etc/redis/redis.conf

  redis-replica3:
    image: redis:${REDIS_VERSION}
    container_name: redis-replica3
    hostname: redis-replica3
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-enabled", "yes", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}", "--masterauth", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "${REDIS_REPLICA_PORT}:6379"
    volumes:
      - ./replica1/data:/data
      - ./replica1/redis.conf:/usr/local/etc/redis/redis.conf
    mem_limit: ${REDIS_MEM_LIMIT}
