version: '3.8'

services:
  registry:
    image: registry:2
    container_name: registry
    restart: always
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    volumes:
      - registry_data:/var/lib/registry
      - ./auth:/auth

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/certs:/etc/nginx/certs:ro
      - ./auth:/auth
    entrypoint: ["/auth/entrypoint.sh"]
    depends_on:
      - registry

  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui
    restart: always
    environment:
      - REGISTRY_TITLE=Docker Registry UI
      - REGISTRY_URL=http://registry:5000
      - DELETE_IMAGES=true  # İmajları silme desteği
    ports:
      - "8081:80"
    depends_on:
      - registry
    

volumes:
  registry_data:

    #cat /auth/htpasswd
    #admin:$2y$05$a8B9/vt1LY2hk.D2qfuYSOmoATEo2Hi9CJVZvWJIon0ZCtp/IH8Xm