services:
  rabbitmq1:
    image: rabbitmq:3.13.2-management
    hostname: rabbitmq1
    network_mode: host
    environment:
      RABBITMQ_ERLANG_COOKIE: "skIJni56i1Zas1Z3PTLoJSgMx9O8"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    ports:
      - "15672:15672"
      - "5672:5672"
    command: >
      sh -c "rabbitmq-server & sleep 30 &&
      rabbitmqctl stop_app &&
      rabbitmqctl reset &&
      rabbitmqctl start_app &&
      tail -f /dev/null"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure