apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cluster-config
  namespace: {{ .Values.namespace }}
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode yes
    port 6379
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    daemonize no
    supervised no
    pidfile /var/run/redis_6379.pid
    loglevel notice
    logfile ""
    databases 16
    always-show-logo yes
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir ./
    requirepass ServicePassword
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
    rename-command CONFIG ""
    rename-command SHUTDOWN ""
    rename-command BGREWRITEAOF ""
    rename-command BGSAVE ""
    rename-command SAVE ""
    rename-command RESTORE ""
    rename-command MIGRATE ""
    rename-command DUMP ""
    rename-command DEBUG ""
    rename-command OBJECT ""
    rename-command MONITOR ""
    rename-command SLAVEOF ""
    rename-command REPLICAOF ""
    rename-command ROLE ""
    rename-command PUBLISH ""
    rename-command PUBSUB ""
    rename-command SCRIPT ""
    rename-command SLOWLOG ""
    rename-command SYNC ""
    rename-command PSYNC ""
    rename-command CLIENT ""
    rename-command CLUSTER ""
    rename-command INFO ""
    rename-command MEMORY ""
    rename-command LATENCY ""
    rename-command ACL ""
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: local-provisioner-config
  namespace: kube-system
data:
  storageClassMap: |
    local-storage:
      hostDir: /mnt/disks
      mountDir: /mnt/disks
      blockCleanerCommand:
        - "/scripts/shred.sh"
        - "2"
      volumeMode: Filesystem
      fsType: ext4
      recycler:
        command:
          - "/scripts/shred.sh"
          - "2"
        timeout: 60
      storageClassName: local-storage

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: local-volume-provisioner  # DaemonSet adıyla aynı olmalı
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-provisioner-sa
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: local-provisioner-role
rules:
- apiGroups: [""]
  resources: ["nodes", "persistentvolumes"]
  verbs: ["get", "list", "watch", "create", "delete", "update"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims", "events"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-provisioner-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: local-provisioner-role
subjects:
- kind: ServiceAccount
  name: local-provisioner-sa
  namespace: kube-system
---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: setup-disks
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: setup-disks
  template:
    metadata:
      labels:
        app: setup-disks
    spec:
      containers:
      - name: setup-disks
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "dd if=/dev/zero of=/mnt/disks/redis-test.img bs=1M count=1024 && \
                mkfs.ext4 /mnt/disks/redis-test.img && \
                mkdir -p /mnt/disks/redis-test && \
                mount -o loop /mnt/disks/redis-test.img /mnt/disks/redis-test && \
                chmod 777 /mnt/disks/redis-test && \
                dd if=/dev/zero of=/mnt/disks/redis-test-1.img bs=1M count=1024 && \
                mkfs.ext4 /mnt/disks/redis-test-1.img && \
                mkdir -p /mnt/disks/redis-test-1 && \
                mount -o loop /mnt/disks/redis-test-1.img /mnt/disks/redis-test-1 && \
                chmod 777 /mnt/disks/redis-test-1 && \
                while true; do sleep 3600; done"]
        volumeMounts:
        - name: local-disks
          mountPath: /mnt/disks
      volumes:
      - name: local-disks
        hostPath:
          path: /mnt/disks
      tolerations:
      - key: node.kubernetes.io/not-ready
        operator: Exists
        effect: NoSchedule
      - key: node.kubernetes.io/unreachable
        operator: Exists
        effect: NoSchedule


---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: local-volume-provisioner  # StorageClass provisioner adıyla aynı olmalı
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: local-volume-provisioner  # Labels'in de uyumlu olduğundan emin olun
  template:
    metadata:
      labels:
        app: local-volume-provisioner  # Labels'in de uyumlu olduğundan emin olun
    spec:
      serviceAccountName: local-provisioner-sa
      containers:
      - name: provisioner
        image: quay.io/external_storage/local-volume-provisioner:latest
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - mountPath: /mnt/disks
          name: local-disks
        - mountPath: /etc/provisioner/config/storageClassMap
          name: provisioner-config
          subPath: storageClassMap
      volumes:
      - name: local-disks
        hostPath:
          path: /mnt/disks
      - name: provisioner-config
        configMap:
          name: local-provisioner-config


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-test
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disks/redis-test
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - iagkbrntsts02

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc-test
  namespace: redis-ns
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "redis-cluster"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: redis-cluster
  template:
    metadata:
      labels:
        app: redis-cluster
    spec:
      containers:
      - name: redis-cluster
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-storage
          mountPath: /data
        - name: redis-cluster-config
          mountPath: /usr/local/etc/redis/redis.conf
          subPath: redis.conf
        command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-enabled", "yes", "--appendonly", "yes"]
      volumes:
      - name: redis-cluster-config
        configMap:
          name: redis-cluster-config
  volumeClaimTemplates:
    - metadata:
        name: redis-storage
      spec:
        storageClassName: "{{ .Values.persistence.storageClass }}"
        accessModes: [ "{{ .Values.persistence.accessMode }}" ]
        resources:
          requests:
            storage: "{{ .Values.persistence.size }}"

---

apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 6379
      name: redis-cluster
  clusterIP: None
  selector:
    app: redis-cluster