# templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-cluster
  template:
    metadata:
      labels:
        app: redis-cluster
    spec:
      containers:
        - name: redis-cluster-container
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: redis-cluster-storage
              mountPath: /usr/share/nginx/html
      volumes:
        - name: redis-cluster-storage
          persistentVolumeClaim:
            claimName: redis-cluster-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
spec:
  selector:
    app: redis-cluster
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
