# templates/deployment.yaml
# templates/statefulset.yaml

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
spec:
  serviceName: "redis-cluster"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: redis-cluster
  template:
    metadata:
      labels:
        app: redis-cluster
    spec:
      containers:
        - name: redis-cluster
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-cluster-data
              mountPath: /data
          command: ["redis-cluster-server", "--cluster-enabled", "yes", "--appendonly", "yes"]
  volumeClaimTemplates:
    - metadata:
        name: redis-cluster-data
      spec:
        accessModes: [ "{{ .Values.persistence.accessMode }}" ]
        resources:
          requests:
            storage: "{{ .Values.persistence.size }}"


---

apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
spec:
  ports:
    - port: 6379
      name: redis-cluster
  clusterIP: None
  selector:
    app: redis-cluster
