apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "redis-cluster"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: redis-cluster
  template:
    metadata:
      labels:
        app: redis-cluster
    spec:
      containers:
        - name: redis-cluster
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-cluster-data
              mountPath: /data
            - name: redis-cluster-config
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
          command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--cluster-enabled", "yes", "--appendonly", "yes"]
  volumeClaimTemplates:
    - metadata:
        name: redis-cluster-data
        namespace: {{ .Values.namespace }}
      spec:
        accessModes: [ "{{ .Values.persistence.accessMode }}" ]
        resources:
          requests:
            storage: "{{ .Values.persistence.size }}"
  volumes:
    - name: redis-cluster-config
      configMap:
        name: redis-cluster-config

---

apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 6379
      name: redis-cluster
  clusterIP: None
  selector:
    app: redis-cluster

