kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv
  namespace: {{ .Values.namespace }}
  labels:
    app: vizyoneks
    service: redis
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standart
  hostPath:
    path: "/mnt/data/redis"

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: vizyoneks
    service: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standart

kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  labels:
    app: vizyoneks
    service: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis
  template:
    metadata:
      labels:
        app: vizyoneks
        service: redis
    spec:
      containers:
        - name: redis
          image: redis
          imagePullPolicy: IfNotPresent
          args:
            - "--requirepass {{ .Values.redisPassword }}"
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
      automountServiceAccountToken: false
kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  labels:
    app: vizyoneks
    service: redis
spec:
  selector:
    app: vizyoneks
    service: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP
