services:
  rabbitmq2:
    image: rabbitmq:3.13.2-management
    hostname: rabbitmq2
    network_mode: host
    environment:
      RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    ports:
      - "15672:15672"
      - "5672:5672"
    command: >
      sh -c "rabbitmq-server & sleep 30 &&
      rabbitmqctl stop_app &&
      rabbitmqctl reset &&
      while ! rabbitmqctl node_health_check --node rabbit@rabbitmq1; do sleep 5; done &&
      rabbitmqctl join_cluster rabbit@rabbitmq1 &&
      rabbitmqctl start_app &&
      tail -f /dev/null"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure