version: "3.8"

volumes:
  redisdata:
    driver: local

networks:
  default:
    name: redis
    external: false

services:
  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - 6379:6379
    environment:
      - REDIS-PWD=${REDIS_PASSWORD}
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 10
    mem_limit: ${REDIS_MEM_LIMIT}
  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - 5540:5540
    restart: always
    volumes:
      - redisdata:/db
    environment:
      - REDIS_HOSTS=10.134.11.215:8080
      - maxRetriesPerRequest=5
      - maxConnections=100
      - maxConnectionsPerEndpoint=50
      - maxConnectionsPerRequest=50
      - maxRetriesPerEndpoint=5
      - maxRetryTime=3000
      - maxRetryDelay=3000
      - maxPoolSize=100
      - minPoolSize=1
      - poolTimeout=500
      - idleTime=1800000
      - connectTimeout=1000
      - enableTLS=false
      - enableDNSDiscovery=false
      - enableAutoPipelining=true
      - enableClientSideCaching=false
      - enableOptimisticPipelining=false
